artifact_location: file:///C:/Users/Avinash/Desktop/New folder (2)/sytescan/backend/runs/mlflow/0
creation_time: 1762321198418
experiment_id: '0'
last_update_time: 1762321198418
lifecycle_stage: active
name: Default
