artifact_location: file:///C:/Users/Avinash/Desktop/New folder (2)/sytescan/backend/runs/mlflow/351551405583072265
creation_time: 1762321198463
experiment_id: '351551405583072265'
last_update_time: 1762321198463
lifecycle_stage: active
name: francesco_training\models
